# Generated by Django 5.0.6 on 2024-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_category_name_alter_taskitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
