# Generated by Django 5.0.6 on 2024-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='prio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='progress',
            field=models.CharField(choices=[('Todo', 'ToDO'), ('inProgress', 'inProgress'), ('Await_Feedback', 'Await_Feedback'), ('Done', 'Done')], default='Todo', max_length=14),
        ),
    ]
