# Generated by Django 5.0.6 on 2024-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_taskitem_prio_taskitem_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='users',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tasks', to='join.contact'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='progress',
            field=models.CharField(choices=[('Todo', 'ToDo'), ('inProgress', 'In Progress'), ('Await_Feedback', 'Await Feedback'), ('Done', 'Done')], default='Todo', max_length=14),
        ),
    ]
