# Generated by Django 5.0.6 on 2024-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_remove_taskitem_users_alter_taskitem_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='subtasks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
