# Generated by Django 5.0.6 on 2024-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_taskitem_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='parent_task', to='join.subtaskitem'),
        ),
    ]
