# Generated by Django 5.0.6 on 2024-08-02 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_rename_taskitem_subtaskitem_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtaskitem',
            old_name='task',
            new_name='parent_task',
        ),
        migrations.AddField(
            model_name='subtaskitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtaskitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
