# Generated by Django 5.0.6 on 2024-08-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0012_rename_task_subtaskitem_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
