# Generated by Django 5.0.6 on 2024-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0013_alter_subtaskitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Technical', 'Technical')], default='User', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SubTaskItem',
        ),
    ]
