# Generated by Django 5.0.6 on 2024-08-08 12:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('join', '0014_remove_taskitem_assigned_to_alter_category_color_and_more'),
    ]

    operations = [
    ]
