# Generated by Django 5.0.6 on 2024-08-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0015_create_default_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='category',
        ),
    ]
